In [8]:
%matplotlib notebook
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow import keras

In [75]:
mu, sigma = 2, 0.9
x1 = np.random.normal(mu, sigma, 100)
#x1 = np.arange(1,100)
x2 = np.random.normal(loc=x1, scale=2)
y = np.random.normal(loc=x1+x2, scale=1)
x = np.concatenate([x1.reshape(-1, 1), x2.reshape(-1, 1)], 1)

In [76]:
model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[2])])
model.compile(optimizer='sgd', loss='mean_squared_error')
model.fit(x, y, epochs=500)

Train on 100 samples
Epoch 1/500
100/100 [==============================] - 0s 1ms/sample - loss: 37.4662
Epoch 2/500
100/100 [==============================] - 0s 109us/sample - loss: 4.7706
Epoch 3/500
100/100 [==============================] - 0s 133us/sample - loss: 1.4704
Epoch 4/500
100/100 [==============================] - 0s 72us/sample - loss: 1.0853
Epoch 5/500
100/100 [==============================] - 0s 147us/sample - loss: 1.0514
Epoch 6/500
100/100 [==============================] - 0s 84us/sample - loss: 1.0457
Epoch 7/500
100/100 [==============================] - 0s 88us/sample - loss: 1.0722
Epoch 8/500
100/100 [==============================] - 0s 91us/sample - loss: 1.0654
Epoch 9/500
100/100 [==============================] - 0s 80us/sample - loss: 1.0330
Epoch 10/500
100/100 [==============================] - 0s 134us/sample - loss: 1.0517
Epoch 11/500
100/100 [==============================] - 0s 84us/sample - loss: 1.0314
Epoch 12/500
100/100 [================

100/100 [==============================] - 0s 76us/sample - loss: 1.0103
Epoch 96/500
100/100 [==============================] - 0s 82us/sample - loss: 0.9866
Epoch 97/500
100/100 [==============================] - 0s 110us/sample - loss: 0.9878
Epoch 98/500
100/100 [==============================] - 0s 154us/sample - loss: 1.0731
Epoch 99/500
100/100 [==============================] - 0s 82us/sample - loss: 1.0107
Epoch 100/500
100/100 [==============================] - 0s 81us/sample - loss: 0.9949
Epoch 101/500
100/100 [==============================] - 0s 88us/sample - loss: 0.9958
Epoch 102/500
100/100 [==============================] - 0s 80us/sample - loss: 0.9992
Epoch 103/500
100/100 [==============================] - 0s 91us/sample - loss: 1.0077
Epoch 104/500
100/100 [==============================] - 0s 96us/sample - loss: 1.0966
Epoch 105/500
100/100 [==============================] - 0s 78us/sample - loss: 1.0405
Epoch 106/500
100/100 [==============================] - 0s

Epoch 189/500
100/100 [==============================] - 0s 87us/sample - loss: 0.9965
Epoch 190/500
100/100 [==============================] - 0s 84us/sample - loss: 1.0168
Epoch 191/500
100/100 [==============================] - 0s 93us/sample - loss: 0.9841
Epoch 192/500
100/100 [==============================] - 0s 78us/sample - loss: 0.9858
Epoch 193/500
100/100 [==============================] - 0s 98us/sample - loss: 0.9821
Epoch 194/500
100/100 [==============================] - 0s 77us/sample - loss: 0.9968
Epoch 195/500
100/100 [==============================] - 0s 99us/sample - loss: 1.0106
Epoch 196/500
100/100 [==============================] - 0s 96us/sample - loss: 1.0046
Epoch 197/500
100/100 [==============================] - 0s 95us/sample - loss: 1.0022
Epoch 198/500
100/100 [==============================] - 0s 105us/sample - loss: 0.9887
Epoch 199/500
100/100 [==============================] - 0s 76us/sample - loss: 0.9913
Epoch 200/500
100/100 [===================

100/100 [==============================] - 0s 94us/sample - loss: 0.9998
Epoch 283/500
100/100 [==============================] - 0s 88us/sample - loss: 0.9897
Epoch 284/500
100/100 [==============================] - 0s 114us/sample - loss: 1.0178
Epoch 285/500
100/100 [==============================] - 0s 84us/sample - loss: 0.9929
Epoch 286/500
100/100 [==============================] - 0s 89us/sample - loss: 0.9884
Epoch 287/500
100/100 [==============================] - 0s 90us/sample - loss: 0.9959
Epoch 288/500
100/100 [==============================] - 0s 75us/sample - loss: 0.9833
Epoch 289/500
100/100 [==============================] - 0s 85us/sample - loss: 0.9866
Epoch 290/500
100/100 [==============================] - 0s 90us/sample - loss: 0.9950
Epoch 291/500
100/100 [==============================] - 0s 69us/sample - loss: 0.9844
Epoch 292/500
100/100 [==============================] - 0s 102us/sample - loss: 0.9938
Epoch 293/500
100/100 [==============================] 

100/100 [==============================] - 0s 80us/sample - loss: 1.0053
Epoch 376/500
100/100 [==============================] - 0s 90us/sample - loss: 0.9982
Epoch 377/500
100/100 [==============================] - 0s 77us/sample - loss: 1.0015
Epoch 378/500
100/100 [==============================] - 0s 89us/sample - loss: 1.0353
Epoch 379/500
100/100 [==============================] - 0s 85us/sample - loss: 1.0061
Epoch 380/500
100/100 [==============================] - 0s 75us/sample - loss: 1.0130
Epoch 381/500
100/100 [==============================] - 0s 91us/sample - loss: 0.9968
Epoch 382/500
100/100 [==============================] - 0s 78us/sample - loss: 0.9834
Epoch 383/500
100/100 [==============================] - 0s 95us/sample - loss: 0.9836
Epoch 384/500
100/100 [==============================] - 0s 81us/sample - loss: 1.0233
Epoch 385/500
100/100 [==============================] - 0s 85us/sample - loss: 0.9915
Epoch 386/500
100/100 [==============================] - 

Epoch 469/500
100/100 [==============================] - 0s 79us/sample - loss: 0.9823
Epoch 470/500
100/100 [==============================] - 0s 79us/sample - loss: 0.9967
Epoch 471/500
100/100 [==============================] - 0s 102us/sample - loss: 1.0684
Epoch 472/500
100/100 [==============================] - 0s 78us/sample - loss: 0.9824
Epoch 473/500
100/100 [==============================] - 0s 92us/sample - loss: 1.0080
Epoch 474/500
100/100 [==============================] - 0s 82us/sample - loss: 0.9976
Epoch 475/500
100/100 [==============================] - 0s 73us/sample - loss: 0.9828
Epoch 476/500
100/100 [==============================] - 0s 92us/sample - loss: 0.9938
Epoch 477/500
100/100 [==============================] - 0s 71us/sample - loss: 1.0010
Epoch 478/500
100/100 [==============================] - 0s 71us/sample - loss: 0.9858
Epoch 479/500
100/100 [==============================] - 0s 112us/sample - loss: 0.9880
Epoch 480/500
100/100 [==================

In [77]:
model.weights

[<tf.Variable 'dense_15/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[1.032452 ],
        [0.9636079]], dtype=float32)>,
 <tf.Variable 'dense_15/bias:0' shape=(1,) dtype=float32, numpy=array([-0.15897453], dtype=float32)>]

In [79]:
model.predict([[ 1.68865182,  1.56145156]])

array([[3.0891047]], dtype=float32)

In [73]:
y

array([ 4.00551945,  8.15086732,  5.30310791,  5.36556103,  2.94874233,
        1.64172506,  3.39892436,  4.95479092,  7.61639662,  3.9675906 ,
        5.63585713,  0.55823714,  3.42220184,  6.82815422,  4.13508476,
        7.46681412,  2.60706532,  1.77863908,  8.38554135,  3.43761878,
        3.23223714,  0.39907056,  3.32589542,  6.46144935,  3.07423   ,
        4.89649352,  4.35346652, -0.74485401,  6.0062707 ,  6.7335785 ,
        4.34114693,  1.36768665,  2.65884339,  2.53156   ,  3.8109356 ,
        3.26166497,  2.94475827,  3.76545084,  4.76624648,  6.06549566,
        0.0862627 ,  1.77769423,  0.94402316,  4.0078869 ,  5.04748666,
        5.00719728,  4.10542913,  4.62389751,  5.9158247 ,  1.58208132,
        2.66978297, -1.58705684,  1.36283421,  2.29078709,  1.87861991,
        2.24818796,  5.06420021,  4.51300852,  2.89638847,  0.4567938 ,
        5.96165072,  4.80028313,  4.05211148,  4.4914382 ,  5.47982961,
        2.59808701,  8.19833614,  3.00884926,  4.10767207,  3.77

In [78]:
x

array([[ 1.68865182,  1.56145156],
       [ 3.32242705,  3.57220125],
       [ 2.01078114,  4.55601791],
       [ 1.79007511,  0.71607602],
       [ 4.19283311,  3.57292314],
       [ 2.98292623,  3.99547741],
       [ 1.29423516,  3.36507203],
       [ 2.78898073,  3.76493685],
       [ 2.46677767,  0.31035601],
       [ 2.79710466,  5.72499422],
       [ 3.77003753,  3.59078187],
       [ 2.44163843,  1.61898569],
       [ 3.32372642,  2.25235171],
       [ 2.87746585,  1.3767045 ],
       [ 2.89144685,  4.75071781],
       [ 0.89882487, -3.84710945],
       [ 2.21703891,  5.02574706],
       [ 2.28823597,  1.70570546],
       [ 1.80165964,  2.36902464],
       [ 2.14177296,  0.77391369],
       [ 1.46977147,  4.75049642],
       [ 2.45374998,  2.56865199],
       [ 1.87243277, -0.70610139],
       [ 3.27431816,  4.47865301],
       [ 2.97754002,  2.29653072],
       [ 3.01913085,  5.75230078],
       [ 1.34925133, -2.61966136],
       [ 2.93081219,  1.17494632],
       [ 1.83031484,